services:
  texasmysql:
    image: mysql:8.0.41
    restart: none
    volumes:
      - /opt/docker/texas/mysql:/var/lib/mysql
    networks:
      - dev_lab
    entrypoint: ["mysqld"]
networks:
  dev_lab:
    external: true
