services:
  texasmysql:
    image: ghcr.io/fineyoungcannibals/texas_mysql:latest
    restart: none
    volumes:
      - /opt/docker/texas/mysql:/var/lib/mysql
    networks:
      - dev_lab
    entrypoint: ["mysqld"]
networks:
  dev_lab:
    external: true
